- hosts: localhost
  vars_files:
    - ./auth_codes/vars.yml
  environment:
    N_PREFIX: "{{ lookup('env', 'HOME') }}/.local/.n"
    PATH: "{{ lookup('env', 'HOME') }}/.local/.n/bin:{{ lookup('env', 'HOME') }}/.local/.npm-global/bin:{{ ansible_env.PATH }}"
  pre_tasks:
    - name: Update Apt
      become: true
      apt:
        force_apt_get: true
        update_cache: true
        state: present
      tags:
        - install
        - core
    - name: Set authorized key took from file
      authorized_key:
        user: "eliag"
        state: present
        key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_ed25519.pub') }}"
      with_fileglob:
      - "{{ lookup('env', 'HOME') }}/.ssh/*.pub"
  tasks:
    - include_tasks: tasks/git-setup.yml
    - include_tasks: tasks/core-setup.yml
    - include_tasks: tasks/node-setup.yml
    - include_tasks: tasks/npm-packages.yml
    - include_tasks: tasks/zsh-setup.yml
    - include_tasks: tasks/dotfiles.yml

    # run container install ansible and run ansible playbook with separated task
